env:
  global:
    - secure: jrac4kP9ahcvZc+ZP1cm504zIxtrs6Gy4cH7mb0kNpYyxSfggBNhtw61Se6l8ta5NCHRQF9WAMzJqCkxaHputWQm3a/uv9oXLDUXzXB6isIFp4ntbFe0EchBGgvYavCuwZCzur9qhQd5c3QmjiuKjiZj0s/fbIYToiwui1CmXpvKGSoMGXVz7tSfUaB91ByZrc8Z8/KjQA/mNhb5+dkFSxe29gRbY5EkUv/D4mRFA/vSVfftw5dC6PkF3SIk31n/RsMjdGXEH3ffVTVBWT4RL42go8t1y6D0JCCHVMzam8fFdH3oBdBzkIwVOSCs9EQYUWtvpDMHjw6i3R0ETOqkc2EUPfYy8Z+5kvDXOEk0SxcUywITrYa8zYXEyK0YL76+ekR5Ca0rgcfGrg5R68S4j4+Trv0I2nYqFXftdT/EAxAlnmnATmxi55RHvbgA+U3anHcGzFPStg0w8MaMbmgTXnlSz8rkCsv0+grGxzcUtuyQEF6oTfCXHM38F8/x948oorstqTAY052YBKSH5J6hjqw4mvHt9TY6MNtOTnUDP2YHtG+mx2HBv/55Dyu/nVJ6E1bLPW27+urjBCjFHrS3JERscmx8XbtWLQZD6z3mHuXWG59tVjytLH6uNvJ2ZufhYmyLZe42rMjG7of3R+0bzbMd0+1Y58oejH9u692mTlU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/quidsup_malicious-sites
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
