env:
  global:
    - secure: SL/6ljHs4GBUojckHUml9tezenLs5IH/faeFEzCNXhfdYVYxqkvcYV4ve/NxJL10GHuN2HW4Bm3iA6aInJM6j7VcSP8G0Lvf9cvX7q01jNmi2Q2JTJFWmlXsq61EHh/J3Ws2OA7PIPIyPI2ibmxqpPxQKAbdnDGabsAJJrVnK4Z8MmUpcmaaFWkT6RSarbpsENA+c1qhl4JZYHms5HstJ9OKVtp5V+ZpX+pBvoD9hCAzdjdbXbwCXZryhllvUpKvgolr/q8VHX6N69sckkOFzPQ8kTWYHKsGGv79eM7gRaHo++fG/UkGrxsHX4HCL0sk5YkGxHgFzyu3Pbls/GqEwCvZVVjfRkCFUiU8pG+Qz/8pwSfrpRaIjjZOHWwPyrzzQc7iVQoB5wI+6svGFHifRt1lKdk0F9o6kDq6DVKfXdXyDNEaMjYCDf/t7HXBLpTUIxPXZpoARZlUEebKCyXxs8V5X5g4I5MtdCUXVC0vmz0ZQIW6JUCv3YyRASNNE2MZT2sti5UxloOwP/2UyYtdlmgpJpJNxNUIM12lixG7JsgKu7OOmb4eSUlJKV6iw8gDd9UHSVdtacpO6Ms/p2jgpmx1o6Qeqa/HVfjI43vQ9SS0foEBwTQuFVGzhSAoojCllbZJ+9+yxJWT77acgykJbnKGbKeRdrEbU75bAU7JtJI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/quidsup_malicious-sites
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
