env:
  global:
    - secure: W/e/0lbev5hkoDz+GWYCYuIdswsog27IyhdShSyDQYAPGgI6qRgS+Ccs0Jqq6btxmZ7WV31DnUQXcSXBvWzQdT4U3pHGA6SP7BrnpaAJTskj1qlb01J649k7XBPcYXfqRh3cyoGfp0JK01zbr+ZxUe2JNoBduUPUKDrUm4g6J+pbCOfQNhyVG1WCgBuhf2HZLXBU4S+1RMm+VhcKlC1KtlHCz18szvrKx3nH1jezfXk+n87VxA1Na1E4JduyDswsJvyEW11x8OG7C1Cie3E1kMfajYvT30NlQ6YMpPn8n2nuZCTof8d+KYJiDi77lwVOAP2nPSAJ7ggcqwp6W0U/jkjrZ0sRPUQWoZUvhlK5EUjweT4Rv8LBZ7nDyY6VTYBJma6docuqoDyPNSGa88x70xh4tq49Z9n2cDzkagN0dlXLiNt4vslB4luFvybeNMPaghRo0lQCLMWiCuIJc9i1LnY8wkiok1IObFtyQ3h6LY3oXVmA6nYry2b91IOOJYrjN2XKVwzTMjYXqum1opPl8LnhtsbToC6wbw3WSq+36Qdu+5h58+84Eh9SprNv6ad91uIAt74SrXF5E46t6IUoxLlt0e01z9fPHTSEDvfD6KfVo0jxIhZBkJa32tabY0fBU0nJ09QRXL/LD25rsgVxVEXK5qnkY/otDIrdfGUAo94=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/quidsup_malicious-sites
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - sudo apt-get -y install python3-pip
  - sudo apt-get -y install dos2unix
  - pip3 install colorama

script:
  - export TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}
  - export GH_TOKEN=${GH_TOKEN}
  - export TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
  - export GIT_BRANCH=${GIT_BRANCH}
  - export GIT_EMAIL=${GIT_EMAIL}
  - export GIT_NAME=${GIT_NAME}
  - python3 ./update.py

notifications:
  email: false
